//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmspro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class army
    {
        public int army_id { get; set; }
        public string army_name { get; set; }
        public string army_email { get; set; }
        public string army_mobile { get; set; }
        public string army_posting { get; set; }
        public string army_account_number { get; set; }
        public string army_ifsc_code { get; set; }
        public string army_image { get; set; }
        public string army_wife { get; set; }
        public string army_father { get; set; }
        public string army_address { get; set; }
        public string army_medal { get; set; }
        public string army_counter_strike { get; set; }
        public string army_hurt_count { get; set; }
        public string army_summary { get; set; }
    }
}
