//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmspro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class blog
    {
        public int blog_id { get; set; }
        public string blog_article { get; set; }
        public string blogger_name { get; set; }
        public string blogger_email { get; set; }
        public string blogger_image { get; set; }
        public string blog_image { get; set; }
    }
}
