//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmspro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class craft
    {
        public int craft_id { get; set; }
        public string craft_name { get; set; }
        public string craft_size { get; set; }
        public string craft_weight { get; set; }
        public string craft_specification { get; set; }
        public string craft_image { get; set; }
    }
}
