//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmspro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crime
    {
        public int crime_id { get; set; }
        public string crime_state { get; set; }
        public string crime_city { get; set; }
        public string crime_iframe { get; set; }
        public string crime_rate { get; set; }
        public string crime_title { get; set; }
        public string crime_summary { get; set; }
        public string crime_criminal { get; set; }
        public string crime_control { get; set; }
    }
}
