//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmspro.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMSEntities : DbContext
    {
        public CMSEntities()
            : base("name=CMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<activate> activates { get; set; }
        public DbSet<army> armies { get; set; }
        public DbSet<craft> crafts { get; set; }
        public DbSet<crime> crimes { get; set; }
        public DbSet<invite> invites { get; set; }
        public DbSet<Site> Sites { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<usertype> usertypes { get; set; }
        public DbSet<police> police { get; set; }
        public DbSet<policetype> policetypes { get; set; }
        public DbSet<policework> policeworks { get; set; }
        public DbSet<firapproved> firapproveds { get; set; }
        public DbSet<report> reports { get; set; }
        public DbSet<contact> contacts { get; set; }
        public DbSet<blog> blogs { get; set; }
        public DbSet<firpolouse> firpolice { get; set; }
        public DbSet<approvedfir> approvedfirs { get; set; }
    }
}
