//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmspro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class firapproved
    {
        public int fir_approved_id { get; set; }
        public string fir_title { get; set; }
        public string fir_id { get; set; }
        public string police_id { get; set; }
        public string approve { get; set; }
    }
}
