//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmspro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class firpolouse
    {
        public int approvedfir_id { get; set; }
        public string approvedfir_title { get; set; }
        public string approvedfir_email { get; set; }
        public string approvedfir_police_id { get; set; }
        public string approvedfir_mobile { get; set; }
        public string approved_fir { get; set; }
    }
}
