//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmspro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class policetype
    {
        public int police_type_id { get; set; }
        public string police_id { get; set; }
        public string police_type_name { get; set; }
        public string police_type_link { get; set; }
    }
}
