//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmspro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class police
    {
        public int police_id { get; set; }
        public string police_name { get; set; }
        public string police_mobile { get; set; }
        public string police_email { get; set; }
        public string police_type { get; set; }
        public string police_idcard { get; set; }
        public string police_station { get; set; }
        public string police_state { get; set; }
        public string police_city { get; set; }
        public string police_home_address { get; set; }
        public string police_activation { get; set; }
    }
}
