//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmspro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class policework
    {
        public int police_work_id { get; set; }
        public string police_name { get; set; }
        public string police_mobile { get; set; }
        public string police_email { get; set; }
        public string police_city { get; set; }
        public string police_state { get; set; }
        public string police_status { get; set; }
        public string police_work { get; set; }
        public string police_time { get; set; }
    }
}
