//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmspro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        public int fir_id { get; set; }
        public string fir_title { get; set; }
        public string reporter_name { get; set; }
        public string reporter_mobile { get; set; }
        public string reporter_email { get; set; }
        public string report_for { get; set; }
        public string report_summary { get; set; }
        public string report_image { get; set; }
        public string report_processing { get; set; }
        public string report_city { get; set; }
        public string report_state { get; set; }
        public string report_address { get; set; }
        public string police_id { get; set; }
    }
}
