//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cmspro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_email { get; set; }
        public string user_pwd { get; set; }
        public string user_image { get; set; }
        public string user_epwd { get; set; }
        public string user_type { get; set; }
        public Nullable<int> user_active { get; set; }
        public string user_mobile { get; set; }
    }
}
